[package]
name = "nil"
version = "0.0.0"
edition = "2021"

[dependencies]
la-arena = "0.2.1"
rnix = { git = "https://github.com/oxalica/rnix-parser.git" }
rowan = "0.15.6"
salsa = "0.17.0-pre.2"
smol_str = "0.1.23"

[dev-dependencies]
expect-test = "1.3.0"

[workspace]
members = ["syntax"]
