[workspace]
resolver = "2"
members = [
    "crates/builtin",
    "crates/ide",
    "crates/nil",
    "crates/nix-interop",
    "crates/syntax",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.66"

[profile.dev]
debug = 1
