[package]
name = "nil"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.66"

[dependencies]
anyhow = "1.0.68"
argh = "0.1.10"
codespan-reporting = "0.11.1"
crossbeam-channel = "0.5.6"
ide = { path = "../ide" }
indexmap = "1.9.1"
log = "0.4.17"
lsp-server = "0.7.0"
lsp-types = "0.94.0"
nix-interop = { path = "../nix-interop" }
serde = "1.0.140"
serde_json = "1.0.82"
text-size = "1.1.0"
tracing = { version = "0.1.36", features = ["release_max_level_info"] }

[dependencies.tracing-subscriber]
version = "0.3.15"
default_features = false
features = [
    "env-filter",
    "fmt",
    "smallvec",
    "std",
    "tracing-log",
]

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.137"
