[package]
name = "builtin"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"

[dependencies]
phf = "0.11.1"

[build-dependencies]
phf_codegen = "0.11.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
