[package]
name = "syntax"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = "1.13.0"
regex-automata = "0.2.0"
rowan = "0.15.6"

[dev-dependencies]
expect-test = "1.4.0"
