[package]
name = "syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
once_cell = "1.17.0"
regex-automata = "0.2.0"
rowan = "0.15.6"

[dev-dependencies]
expect-test = "1.4.0"
