[package]
name = "ide"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"

[dependencies]
bitflags = "1.3.2"
builtin = { path = "../builtin" }
either = "1.7.0"
indexmap = "1.9.1"
la-arena = "0.2.1"
ordered-float = "3.0.0"
rowan = "0.15.6"
salsa = "0.17.0-pre.2"
smol_str = "0.1.23"
syntax = { path = "../syntax" }

[dev-dependencies]
anyhow = "1.0.60"
expect-test = "1.3.0"
